version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: drive-api
    build: .
    depends_on:
      - db
    command: >
      sh -c "python manage.py collectstatic --no-input &&
      daphne -b 0.0.0.0 drive.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ${PATH_UPLOADED_DATA}:/var/www/driveapi/media/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
