# Generated by Django 4.0.5 on 2022-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_time', models.TimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
